### ISSUE TITLE
[BUG] Icons not loading

### ISSUE THREAD

**Issue by Pimiovdb** [da-rth/yasb#144]
## Expected Behavior

icons should load in, clean install , no changes to styles
awesome font 5 is installed , same for the bars font, also tried nerd fonts

## Current Behavior

icons stay unloaded, tho if you change the arraignment of the font family some icons load in , the same is you set font weight to 900. 

`* {
    font-family:'Font Awesome 5 Free', 'Courier New', 'bars';
    font-size: 16px;
    color: #f2e5bc;
}`
`.cpu-widget .label,
.wifi-widget .label,
.memory-widget .label,
.traffic-widget .label,
.battery-widget .label {
  padding: 2px 5px;
  font-size: 14px;
  border-radius: 5px;
  /*font-weight: 900;*/
}`

without font weight active:
![afbeelding](https://github.com/da-rth/yasb/assets/90112280/aea5132d-5d74-44cf-b75f-5017bdda84f9)

with font weight active:
![afbeelding](https://github.com/da-rth/yasb/assets/90112280/07b89a4b-10db-4424-8f87-75b900054ef1)

## Steps to Reproduce

1. clean install of komobri
2. clean install of yasb
3. open program's

## Context (Environment)
w11 pro laptop , azuread joined.

**Comment by Pimiovdb** [comment]
i seem to have fixed the nerd font icons, but the Bars icons still not working properly,
here is the code to fix the icons:
`* {
font-family: 'Bars', 'Arial' ;
font-size: 16px;
color: #f2e5bc;
}`

`.container-right .widget * {
color: #242424;
font-family: 'JetBrainsMonoNL Nerd Font';
}`
![afbeelding](https://github.com/da-rth/yasb/assets/90112280/c405122a-5908-4a4c-ae4c-4800ac8152f3)

**Comment by Pimiovdb** [comment]
found a cleaner fix:
* {
    font-family: 'Arial';
    font-size: 16px;
    color: #f2e5bc;
}
.widget .label{
  font-family: 'JetBrainsMonoNL Nerd Font';
}

**Comment by Pimiovdb** [comment]
BTW, this didnt fix the RAM icon tho, and the CPU Bars are not working to so i changed the RAM ICON and changed the CPU Widget to not show Bars:
![afbeelding](https://github.com/da-rth/yasb/assets/90112280/29466f57-dd62-40df-bafb-d154faa2d35e)

**Comment by ryannewcomer** [comment]
Hey! I try your config, but my bar now looks like this:

![image](https://github.com/da-rth/yasb/assets/88273136/e66d6c99-7b63-4ee1-9299-3323e67104f3)
What can I do? I had this:

```css
* {
  /* Bar measurement icons: https://github.com/and3rson/graph-bars-font */
  /* Icon set: https://fontawesome.com/v5.15/how-to-use/on-the-desktop/setup/getting-started */
  font-family: "Arial";
  font-size: 16px;
  color: #f2e5bc;
}

.widget .label {
  font-family: "JetBrainsMonoNL Nerd Font";
}
```
Before I change the font, I can't even see the text. But now I can't see the icon. I also got this error:

![image](https://github.com/da-rth/yasb/assets/88273136/983da1b9-3860-4891-9481-13de80529138)


Any solution?

Many thanks
